
services:
  db:
    image: postgres:latest
    container_name: clinic-managementdb_project
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=clinicdbproject
    ports:
      - "5447:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  postgres-data:

networks:
  blog-network:
    driver: bridge