"""email correction 

Revision ID: 8f9896793a94
Revises: f28bca363c0c
Create Date: 2025-02-15 14:25:40.494424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9896793a94'
down_revision = 'f28bca363c0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'doctors', ['email'])
    op.add_column('patients', sa.Column('email', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'hashed_password')
    op.drop_column('patients', 'email')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'hashed_password')
    # ### end Alembic commands ###
