"""pydantic validation  correction

Revision ID: 971a964a8577
Revises: d3faf2602440
Create Date: 2025-02-15 02:10:36.179375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971a964a8577'
down_revision = 'd3faf2602440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
