"""medicine manufacturer name  correction

Revision ID: d3faf2602440
Revises: 0ae41f81dde1
Create Date: 2025-02-15 02:05:22.552568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3faf2602440'
down_revision = '0ae41f81dde1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
