"""authentication and authorization

Revision ID: f28bca363c0c
Revises: 971a964a8577
Create Date: 2025-02-15 14:07:44.970023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28bca363c0c'
down_revision = '971a964a8577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('doctors', sa.Column('email', sa.String(), nullable=False))
    op.add_column('doctors', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute("UPDATE doctors SET hashed_password = 'default_hashed_value' WHERE hashed_password IS NULL")

    # Now enforce NOT NULL constraint
    op.alter_column('doctors', 'hashed_password', nullable=False)

    op.create_unique_constraint(None, 'doctors', ['email'])
    op.add_column('patients', sa.Column('email', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'hashed_password')
    op.drop_column('patients', 'email')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'hashed_password')
    # op.drop_column('doctors', 'email')
    # ### end Alembic commands ###
