"""password manager add

Revision ID: ff11bd0c618a
Revises: 7f0477a4cd63
Create Date: 2025-02-16 18:54:30.065260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff11bd0c618a'
down_revision = '7f0477a4cd63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('doctors', sa.Column('password', sa.String(), nullable=True))
    # op.drop_column('doctors', 'hashed_password')
    op.add_column('patients', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('patients', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'password')
    op.add_column('doctors', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'password')
    # ### end Alembic commands ###
